#!/usr/bin/env bash

message="${1}"
title="${2:-Notification}"

if [ -z "$message" ]; then
	echo "Usage: notify <message> [title]"
	exit 1
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
	osascript -e "display notification \"${message}\" with title \"${title}\""
else
	devbridge send notify message="$message" title="$title"
fi